Step 11. Create Web Service
awilliamson1889/web-app pull request #10
Opened 2021-08-05 15:16 UTC by awilliamson1889

2021-08-06 07:18 UTC, jimmyhollywood requested changes
Generaly:
- Tests: as you have a lot of duplicated code (creation application) you can move it to the separate function.
- Tests directory doesn't mirror the structure of the source code. If you have views, service in src -> you should create the same structure in tests folder and put to these dirs corresponding test cases
- The next thing that you have missed - is running your application with gunicorn
Let's update all changes - if you any questions please contact me.

2021-08-06 07:18 UTC, jimmyhollywood commented on department_app/rest/address_api.py
> +class AddressInfo(Resource):
For API endpoint names let's use the next naming:
- for the single entity - just a name of class (AddressInfo -> Address)
- for the list of entities - postfix 'list' (AllAddressesInfo -> AddressList)
And the same for all endpoints

2021-08-06 07:18 UTC, jimmyhollywood commented on .github/workflows/build.yml
> +          python init_test_data.py
This is not so good way to initialize database with test data. You can use migration or fixtures

2021-08-06 07:18 UTC, jimmyhollywood commented on department_app/__init__.py
>      return app
As you're using app factory - move the code from __init__.py to the app.py file

2021-08-06 07:18 UTC, jimmyhollywood commented on department_app/rest/address_api.py
> +        if not str(address_id).isdigit():
As I understand you have implemented validation using Pydantic, right? Can we now use these classes (pydantic) to validate requests?

2021-08-06 07:18 UTC, jimmyhollywood commented on department_app/tests/factoryes/department_factory.py
factoryes -> factories

2021-08-17 14:26 UTC, jimmyhollywood requested changes

2021-08-17 14:26 UTC, jimmyhollywood commented on config.py
> +configs = {'Prod': ProductionConfig,
This is not needed here. When you run app using gunicorn just use environment variable with name of config class (Development, Production, Testing)

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/app.py
> +MIGRATION_DIR = os.path.join('department_app/migrations')
Move to config

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/app.py
> +    app.config.from_object("config." + config)
Just use env variable in appropriate format (and add note in readme):
```export APP_SETTINGS=config.DevelopmentConfig```

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/app.py
> +    from department_app.models import EmployeeModel, DepartmentModel, PermissionModel,\
Check these imports. They might be avoided

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/app.py
> +    from department_app.views.routes import frontend
Let's put all import one by one in the same place

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/fixtures/address.yaml
> +  - id: 1
Do you really need to define the ids? The same for others yaml files

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/models/__init__.py
> +from flask_sqlalchemy import SQLAlchemy
You should not import in the init you real dependencies. Let's move it to the separate file (db.py or database.py in the root)

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/models/__init__.py
> +db = SQLAlchemy()
The same

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/models/address.py
> +db = SQLAlchemy()
This line is duplicated in each model module. This thing should be imported from the single file where it is defined (db.py or database.py)

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/rest/address.py
> +from department_app.models import AddressModel, db
models should not be used in views

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/rest/address.py
> +        return address.dict(), 201
Let's use the same response creation approach (like you've used above with make_response)

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/service/address.py
> +        if not str(address_id).isdigit():
Format validation is implemented in view level and in pydantic. So, here you suppose that data is valid.

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/wsgi.py
> +os.environ['FLASK_CONFIG'] = 'TestingConfig'
This should not be here. Instead use export (on linux) command.

2021-08-17 14:26 UTC, jimmyhollywood commented on .github/workflows/build.yml
> +          pip install -r CI-requirements.txt
requirements.txt
```
flask==1.1.1
pydantic==1.1.1
...
```
test_requirements.txt
```
-r requirements.txt
pytest==1.1.1
```

2021-08-17 14:26 UTC, jimmyhollywood commented on .pylintrc
>        mypy.py,
mypy still exist here?

2021-08-17 14:26 UTC, jimmyhollywood commented on README.md
>  $ flask db migrate -m "Initial migration."
Migration files should be presented in sources. User should not generate these files himself

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/service/address.py
> +        except DataError as exception:
Each exception should be handled. In this case you should store an error message in log file. And then - reraise exception

2021-08-17 14:26 UTC, jimmyhollywood commented on department_app/service/address.py
> +        address = CRUDAddress.get(address_id)
Let's use the following approach:
```
try:
    # We don't need to check whether record is existing - we just trying to update it
    address_model.query.update(name=name).where(id=id) # i am no sure about syntax
except IntegrityError:
    log.write(msg="Address with id %d does not exist")
    raise # or return False
return True
```

2021-08-17 14:45 UTC, awilliamson1889 commented on config.py
> +configs = {'Prod': ProductionConfig,
Unnecessary variable deleted.

2021-08-17 15:19 UTC, awilliamson1889 commented on department_app/app.py
> +    from department_app.models import EmployeeModel, DepartmentModel, PermissionModel,\
These imports already deleted.

2021-08-17 15:22 UTC, awilliamson1889 commented on department_app/app.py
> +    from department_app.views.routes import frontend
The imports location has been changed.

2021-08-17 16:46 UTC, awilliamson1889 commented on .github/workflows/build.yml
> +          pip install -r CI-requirements.txt
"CI-requirements.txt" updated.

2021-08-18 14:18 UTC, awilliamson1889 commented on department_app/fixtures/address.yaml
> +  - id: 1
"id" fields deleted.

2021-08-18 14:20 UTC, awilliamson1889 commented on department_app/models/__init__.py
> +from flask_sqlalchemy import SQLAlchemy
This import already deleted.

2021-08-18 14:22 UTC, awilliamson1889 commented on department_app/models/__init__.py
> +db = SQLAlchemy()
This import already deleted.

2021-08-18 14:24 UTC, awilliamson1889 commented on department_app/rest/address.py
> +from department_app.models import AddressModel, db
This import already deleted.

2021-08-18 14:31 UTC, awilliamson1889 commented on department_app/rest/address.py
> +        return address.dict(), 201
All implemented methods have same return format..

2021-08-18 16:33 UTC, awilliamson1889 commented on department_app/service/address.py
> +        except DataError as exception:
Now error message storing in "app.log" file.

2021-08-18 16:38 UTC, awilliamson1889 commented on department_app/service/address.py
> +        address = CRUDAddress.get(address_id)
This method not check address existence, address check existence happens in REST module.

Now error message storing in "app.log" file.

2021-08-18 20:33 UTC, awilliamson1889 commented on .pylintrc
>        mypy.py,
Deleted.

2021-08-19 09:26 UTC, awilliamson1889 commented on README.md
>  $ flask db migrate -m "Initial migration."
Now migration files presented in source.

2021-08-19 09:27 UTC, awilliamson1889 commented on department_app/app.py
> +    app.config.from_object("config." + config)
Now create_app method use ENV variable.

2021-08-19 09:31 UTC, awilliamson1889 commented on department_app/app.py
> +MIGRATION_DIR = os.path.join('department_app/migrations')
"MIGRATION_DIR" moved to config.

2021-08-19 10:16 UTC, awilliamson1889 commented on department_app/wsgi.py
> +os.environ['FLASK_CONFIG'] = 'TestingConfig'
Done.

2021-08-20 12:21 UTC, jimmyhollywood requested changes

2021-08-20 12:21 UTC, jimmyhollywood commented on .github/workflows/build.yml
> +          pip install -r CI-requirements.txt
So then it's enough to install only CI-requirements.txt

2021-08-20 12:21 UTC, jimmyhollywood commented on .github/workflows/build.yml
> +          export APP_SETTINGS=department_app.config.TestingConfig
I definitely don't like this prefix `department_app`

2021-08-20 12:21 UTC, jimmyhollywood commented on README.md
> +export APP_SETTINGS=department_app.config.ProductionConfig
The same - prefix

2021-08-20 12:21 UTC, jimmyhollywood commented on department_app/rest/address.py
> +        Address.check_exist(address_id, address)
Which kind of check is performed here?

2021-08-20 12:21 UTC, jimmyhollywood commented on department_app/rest/address.py
> +        return make_response(jsonify(result), 201)
Again, I see business logic in this view.

2021-08-31 17:55 UTC, jimmyhollywood approved these changes

2021-08-31 17:55 UTC, jimmyhollywood commented on department_app/service/permission.py
> +        except IntegrityError as exception:
Just to note: you can get rid of `as exception` and just use `raise`. Looks like:
```
try:
    # bad code
except IntegrityError:
    # doing smth useful
    raise # will just raise the latest exception
```

2021-08-31 17:58 UTC, jimmyhollywood commented
I see failed check in action pipeline and unresolved conflicts. So, please check your pipeline (maybe it makes sense to define some threshold value for coverage) and resolve conflicting files before merging.

2021-09-01 19:09 UTC, merged